services:
  postgres:
    image: postgres:16-alpine@sha256:57c72fd2a128e416c7fcc499958864df5301e940bca0a56f58fddf30ffc07777
    environment:
      POSTGRES_USER: reimbursement
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reimbursement_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reimbursement"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:v1.0.1@sha256:8d76a3d4ffa32a3661311944007a415332c4bb855657f4f6c57996405c009bea
    ports:
      - "1025:1025"
      - "8025:8025"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.36.0@sha256:37493d0f2e764467421ffe16eb3caa39277e5fa7f6adea18eb5bbfb3c5247f98
    command: azurite-blob --blobHost 0.0.0.0 --blobPort 10000
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/data
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "10000"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
  azurite_data:
